"""empty message

Revision ID: 87c82bb6a9de
Revises: d443a39bb7ef
Create Date: 2024-07-09 20:52:32.194956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c82bb6a9de'
down_revision = 'd443a39bb7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint('client_phone_key', type_='unique')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint('providers_identity_number_key', type_='unique')
        batch_op.drop_constraint('providers_number_company_key', type_='unique')
        batch_op.drop_constraint('providers_phone_key', type_='unique')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('url_image',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.create_unique_constraint('user_email_key', ['email'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('url_image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_unique_constraint('providers_phone_key', ['phone'])
        batch_op.create_unique_constraint('providers_number_company_key', ['number_company'])
        batch_op.create_unique_constraint('providers_identity_number_key', ['identity_number'])
        batch_op.alter_column('url_image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint('client_phone_key', ['phone'])
        batch_op.alter_column('url_image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
